# Generated by Django 3.1 on 2021-04-24 18:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Leaderboard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=datetime.date.today)),
                ('first', models.BooleanField(default=False)),
                ('second', models.BooleanField(default=False)),
                ('username', models.CharField(max_length=150)),
                ('weekly', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Questions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=datetime.date.today)),
                ('first', models.URLField()),
                ('second', models.URLField()),
                ('dif', models.CharField(choices=[('school', 'school'), ('basic', 'basic'), ('easy', 'easy'), ('medium', 'medium'), ('hard', 'hard')], max_length=128)),
            ],
        ),
    ]
