# Generated by Django 3.1 on 2021-04-24 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gfg', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='questions',
            name='dif',
        ),
        migrations.AddField(
            model_name='questions',
            name='dif1',
            field=models.CharField(blank=True, choices=[('school', 'school'), ('basic', 'basic'), ('easy', 'easy'), ('medium', 'medium'), ('hard', 'hard')], max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='questions',
            name='dif2',
            field=models.CharField(blank=True, choices=[('school', 'school'), ('basic', 'basic'), ('easy', 'easy'), ('medium', 'medium'), ('hard', 'hard')], max_length=128, null=True),
        ),
    ]
