# Generated by Django 3.1 on 2021-04-24 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gfg', '0002_auto_20210425_0109'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leaderboard',
            name='username',
            field=models.CharField(max_length=150, unique=True),
        ),
    ]
