# Generated by Django 3.1.5 on 2021-04-25 08:24

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gfg', '0003_auto_20210425_0139'),
    ]

    operations = [
        migrations.CreateModel(
            name='Daily_Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=datetime.date.today)),
            ],
        ),
        migrations.RenameField(
            model_name='questions',
            old_name='dif1',
            new_name='dif',
        ),
        migrations.RenameField(
            model_name='questions',
            old_name='first',
            new_name='question',
        ),
        migrations.RemoveField(
            model_name='questions',
            name='date',
        ),
        migrations.RemoveField(
            model_name='questions',
            name='dif2',
        ),
        migrations.RemoveField(
            model_name='questions',
            name='second',
        ),
        migrations.AddField(
            model_name='questions',
            name='model',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='gfg.daily_question'),
        ),
    ]
