# Generated by Django 3.1.5 on 2021-04-25 08:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gfg', '0005_auto_20210425_0828'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='questions',
            name='model',
        ),
    ]
