# Generated by Django 3.1.5 on 2021-04-25 08:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gfg', '0006_remove_questions_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='questions',
            name='daily_Question',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='gfg.daily_question'),
        ),
    ]
