# Generated by Django 3.1.5 on 2021-04-25 08:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gfg', '0007_questions_daily_question'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='leaderboard',
            name='date',
        ),
        migrations.RemoveField(
            model_name='leaderboard',
            name='first',
        ),
        migrations.RemoveField(
            model_name='leaderboard',
            name='second',
        ),
        migrations.RemoveField(
            model_name='leaderboard',
            name='weekly',
        ),
        migrations.AddField(
            model_name='leaderboard',
            name='daily_Question',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='gfg.daily_question'),
        ),
        migrations.AddField(
            model_name='leaderboard',
            name='questions',
            field=models.ManyToManyField(default=None, to='gfg.Questions'),
        ),
    ]
