# Generated by Django 3.1.5 on 2021-04-25 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gfg', '0008_auto_20210425_1422'),
    ]

    operations = [
        migrations.RenameField(
            model_name='leaderboard',
            old_name='daily_Question',
            new_name='daily_question',
        ),
        migrations.RenameField(
            model_name='questions',
            old_name='daily_Question',
            new_name='daily_question',
        ),
        migrations.RenameField(
            model_name='questions',
            old_name='question',
            new_name='url',
        ),
        migrations.AddField(
            model_name='questions',
            name='name',
            field=models.CharField(max_length=128, null=True),
        ),
    ]
