# Generated by Django 3.1.5 on 2021-04-25 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gfg', '0009_auto_20210425_1435'),
    ]

    operations = [
        migrations.AddField(
            model_name='leaderboard',
            name='weekly_score',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='leaderboard',
            name='questions',
            field=models.ManyToManyField(blank=True, default=None, to='gfg.Questions'),
        ),
    ]
