# Generated by Django 3.1.5 on 2021-04-25 10:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gfg', '0012_leaderboard_daily_question'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='leaderboard',
            name='daily_question',
        ),
    ]
