# Generated by Django 3.1.1 on 2021-01-15 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('tagline', models.TextField()),
                ('github_link', models.URLField()),
                ('github_username', models.CharField(max_length=70)),
                ('linkedin_link', models.URLField()),
                ('country', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('skills', models.TextField()),
                ('languages', models.URLField()),
                ('activity', models.URLField()),
                ('about', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('link', models.URLField()),
                ('image', models.ImageField(default='', upload_to='projects/')),
                ('portfolio', models.ManyToManyField(to='portfolio.Portfolio')),
            ],
        ),
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post', models.CharField(max_length=50)),
                ('company', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('image', models.ImageField(default='', upload_to='projects/')),
                ('portfolio', models.ManyToManyField(to='portfolio.Portfolio')),
            ],
        ),
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('institution', models.CharField(max_length=100)),
                ('image', models.ImageField(default='', upload_to='projects/')),
                ('link', models.URLField()),
                ('portfolio', models.ManyToManyField(to='portfolio.Portfolio')),
            ],
        ),
    ]
